name: Build external contracts

on:
  push:
    branches: [ main ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    
    steps:
        - uses: actions/checkout@v2
          
        - name: Setup Java for publishing on bintray
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
            server-id: bintray-aredzo-mtracker
            server-username: BINTRAY_USERNAME
            server-password: BINTRAY_API_KEY
        - name: Publish on bintray
          run: mvn -B deploy -P bintray
          env:
            BINTRAY_USERNAME: "aredzo"
            BINTRAY_API_KEY: ${{ secrets.BINTRAY_KEY }}
        - name: Setup Java for publish on  github
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Publish package on github packages
          run: mvn -B deploy -P github
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
